name: Test

on:
  push: 
    branches:
      - '*' 

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Listar vari치veis de ambiente
        run: env

      - name: Testar vari치vel
        run: echo "$RODRIGO"

      - name: Testar vari치vel
        run: echo "${{ toJson(github) }}"

      - name: Testar vari치vel
        run: echo "${{ toJson(vars) }}"
